spring.application.name=aseo360
spring.datasource.url=jdbc:mysql://localhost:3306/aseo360?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Seguridad JWT
jwt.secret.key=Esta_Es_Una_Clave_Secreta_Muy_Larga_Y_Segura_Aseo360_PRODUCCION_2026
jwt.expiration.time=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracion de API SUNAT
sunat.api.url=https://app.apisunat.pe/api/v3/documents
sunat.api.voided.url=https://app.apisunat.pe/api/v3/voided
sunat.api.daily-summary.url=https://app.apisunat.pe/api/v3/daily-summary
sunat.api.token=${SUNAT_API_TOKEN:466.mHMNZnwHh83EkkHcRPcEPdLyFeHWuUL1flCJnKB1XJof43vIoJmGGEGFcNtiss9CnWgnzWIXCfhnrqjAOmM8asVPcaaMsUqs7DC5WmNgazkJcKHhANugjWH2}
